### ISSUE TITLE
字体

### ISSUE THREAD

**Issue by sq800** [vscode-ext-studio/vscode-epub-viewer#2]
支持更改字体吗

**Comment by sq800** [comment]
除了预设的五种字体

**Comment by cweijan** [comment]
扩展没提供该设置, 要改有两种方式:
1. clone仓库下来, 编辑样式文件自己打包一个扩展 https://github.com/vscode-ext-studio/vscode-epub-viewer/blob/master/resource/epub/style.css
2. 编辑扩展解压到本地后的样式文件style.css

**Comment by sq800** [comment]
感谢解答
